name: example
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.13.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  country_calling_code_kit:
    path: ../
  material_ui: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
flutter:
  uses-material-design: true