name: country_calling_code_kit
description: "A sleek Flutter package for picking country codes with flags, names, and dial codes. Customizable UI, platform-ready, and user-friendly."
version: 3.0.0
repository: https://github.com/yashas-hm/country-calling-code-kit

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: '>=3.13.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  material_ui: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets: 
    - assets/flags/