library;

import 'package:country_calling_code_kit/src/core/country.dart';

/// A comprehensive list of all countries with their details.
///
/// This list contains [Country] objects for all countries in the world,
/// each with its:
/// - Full name
/// - Country code (as a [CountryCode] enum value)
/// - International calling code (e.g., '+1', '+44')
/// - Flag image asset path
///
/// This list is used as the data source for the country picker UI components
/// and utility functions in this package.
const List<Country> countries = [
  Country(
    countryCode: CountryCode.af,
    name: 'Afghanistan',
    callCode: '+93',
    flag: 'packages/country_calling_code_kit/assets/flags/afg.png',
  ),
  Country(
    countryCode: CountryCode.ax,
    name: 'Åland Islands',
    callCode: '+358',
    flag: 'packages/country_calling_code_kit/assets/flags/ala.png',
  ),
  Country(
    countryCode: CountryCode.al,
    name: 'Albania',
    callCode: '+355',
    flag: 'packages/country_calling_code_kit/assets/flags/alb.png',
  ),
  Country(
    countryCode: CountryCode.dz,
    name: 'Algeria',
    callCode: '+213',
    flag: 'packages/country_calling_code_kit/assets/flags/dza.png',
  ),
  Country(
    countryCode: CountryCode.as,
    name: 'American Samoa',
    callCode: '+1684',
    flag: 'packages/country_calling_code_kit/assets/flags/asm.png',
  ),
  Country(
    countryCode: CountryCode.ad,
    name: 'Andorra',
    callCode: '+376',
    flag: 'packages/country_calling_code_kit/assets/flags/and.png',
  ),
  Country(
    countryCode: CountryCode.ao,
    name: 'Angola',
    callCode: '+244',
    flag: 'packages/country_calling_code_kit/assets/flags/ago.png',
  ),
  Country(
    countryCode: CountryCode.ai,
    name: 'Anguilla',
    callCode: '+1264',
    flag: 'packages/country_calling_code_kit/assets/flags/aia.png',
  ),
  Country(
    countryCode: CountryCode.aq,
    name: 'Antarctica',
    callCode: '+672',
    flag: 'packages/country_calling_code_kit/assets/flags/ata.png',
  ),
  Country(
    countryCode: CountryCode.ag,
    name: 'Antigua and Barbuda',
    callCode: '+1268',
    flag: 'packages/country_calling_code_kit/assets/flags/atg.png',
  ),
  Country(
    countryCode: CountryCode.ar,
    name: 'Argentina',
    callCode: '+54',
    flag: 'packages/country_calling_code_kit/assets/flags/arg.png',
  ),
  Country(
    countryCode: CountryCode.am,
    name: 'Armenia',
    callCode: '+374',
    flag: 'packages/country_calling_code_kit/assets/flags/arm.png',
  ),
  Country(
    countryCode: CountryCode.aw,
    name: 'Aruba',
    callCode: '+297',
    flag: 'packages/country_calling_code_kit/assets/flags/abw.png',
  ),
  Country(
    countryCode: CountryCode.au,
    name: 'Australia',
    callCode: '+61',
    flag: 'packages/country_calling_code_kit/assets/flags/aus.png',
  ),
  Country(
    countryCode: CountryCode.at,
    name: 'Austria',
    callCode: '+43',
    flag: 'packages/country_calling_code_kit/assets/flags/aut.png',
  ),
  Country(
    countryCode: CountryCode.az,
    name: 'Azerbaijan',
    callCode: '+994',
    flag: 'packages/country_calling_code_kit/assets/flags/aze.png',
  ),
  Country(
    countryCode: CountryCode.bs,
    name: 'Bahamas',
    callCode: '+1242',
    flag: 'packages/country_calling_code_kit/assets/flags/bhs.png',
  ),
  Country(
    countryCode: CountryCode.bh,
    name: 'Bahrain',
    callCode: '+973',
    flag: 'packages/country_calling_code_kit/assets/flags/bhr.png',
  ),
  Country(
    countryCode: CountryCode.bd,
    name: 'Bangladesh',
    callCode: '+880',
    flag: 'packages/country_calling_code_kit/assets/flags/bgd.png',
  ),
  Country(
    countryCode: CountryCode.bb,
    name: 'Barbados',
    callCode: '+1246',
    flag: 'packages/country_calling_code_kit/assets/flags/brb.png',
  ),
  Country(
    countryCode: CountryCode.by,
    name: 'Belarus',
    callCode: '+375',
    flag: 'packages/country_calling_code_kit/assets/flags/blr.png',
  ),
  Country(
    countryCode: CountryCode.be,
    name: 'Belgium',
    callCode: '+32',
    flag: 'packages/country_calling_code_kit/assets/flags/bel.png',
  ),
  Country(
    countryCode: CountryCode.bz,
    name: 'Belize',
    callCode: '+501',
    flag: 'packages/country_calling_code_kit/assets/flags/blz.png',
  ),
  Country(
    countryCode: CountryCode.bj,
    name: 'Benin',
    callCode: '+229',
    flag: 'packages/country_calling_code_kit/assets/flags/ben.png',
  ),
  Country(
    countryCode: CountryCode.bm,
    name: 'Bermuda',
    callCode: '+1441',
    flag: 'packages/country_calling_code_kit/assets/flags/bmu.png',
  ),
  Country(
    countryCode: CountryCode.bt,
    name: 'Bhutan',
    callCode: '+975',
    flag: 'packages/country_calling_code_kit/assets/flags/btn.png',
  ),
  Country(
    countryCode: CountryCode.bo,
    name: 'Bolivia (Plurinational State of)',
    callCode: '+591',
    flag: 'packages/country_calling_code_kit/assets/flags/bol.png',
  ),
  Country(
    countryCode: CountryCode.bq,
    name: 'Bonaire, Sint Eustatius and Saba',
    callCode: '+5997',
    flag: 'packages/country_calling_code_kit/assets/flags/bes.png',
  ),
  Country(
    countryCode: CountryCode.ba,
    name: 'Bosnia and Herzegovina',
    callCode: '+387',
    flag: 'packages/country_calling_code_kit/assets/flags/bih.png',
  ),
  Country(
    countryCode: CountryCode.bw,
    name: 'Botswana',
    callCode: '+267',
    flag: 'packages/country_calling_code_kit/assets/flags/bwa.png',
  ),
  Country(
    countryCode: CountryCode.bv,
    name: 'Bouvet Island',
    callCode: '+55',
    flag: 'packages/country_calling_code_kit/assets/flags/bvt.png',
  ),
  Country(
    countryCode: CountryCode.br,
    name: 'Brazil',
    callCode: '+55',
    flag: 'packages/country_calling_code_kit/assets/flags/bra.png',
  ),
  Country(
    countryCode: CountryCode.io,
    name: 'British Indian Ocean Territory',
    callCode: '+246',
    flag: 'packages/country_calling_code_kit/assets/flags/iot.png',
  ),
  Country(
    countryCode: CountryCode.um,
    name: 'United States Minor Outlying Islands',
    callCode: '+246',
    flag: 'packages/country_calling_code_kit/assets/flags/umi.png',
  ),
  Country(
    countryCode: CountryCode.vg,
    name: 'Virgin Islands (British)',
    callCode: '+1284',
    flag: 'packages/country_calling_code_kit/assets/flags/vgb.png',
  ),
  Country(
    countryCode: CountryCode.vi,
    name: 'Virgin Islands (U.S.)',
    callCode: '+1 340',
    flag: 'packages/country_calling_code_kit/assets/flags/vir.png',
  ),
  Country(
    countryCode: CountryCode.bn,
    name: 'Brunei Darussalam',
    callCode: '+673',
    flag: 'packages/country_calling_code_kit/assets/flags/brn.png',
  ),
  Country(
    countryCode: CountryCode.bg,
    name: 'Bulgaria',
    callCode: '+359',
    flag: 'packages/country_calling_code_kit/assets/flags/bgr.png',
  ),
  Country(
    countryCode: CountryCode.bf,
    name: 'Burkina Faso',
    callCode: '+226',
    flag: 'packages/country_calling_code_kit/assets/flags/bfa.png',
  ),
  Country(
    countryCode: CountryCode.bi,
    name: 'Burundi',
    callCode: '+257',
    flag: 'packages/country_calling_code_kit/assets/flags/bdi.png',
  ),
  Country(
    countryCode: CountryCode.kh,
    name: 'Cambodia',
    callCode: '+855',
    flag: 'packages/country_calling_code_kit/assets/flags/khm.png',
  ),
  Country(
    countryCode: CountryCode.cm,
    name: 'Cameroon',
    callCode: '+237',
    flag: 'packages/country_calling_code_kit/assets/flags/cmr.png',
  ),
  Country(
    countryCode: CountryCode.ca,
    name: 'Canada',
    callCode: '+1',
    flag: 'packages/country_calling_code_kit/assets/flags/can.png',
  ),
  Country(
    countryCode: CountryCode.cv,
    name: 'Cabo Verde',
    callCode: '+238',
    flag: 'packages/country_calling_code_kit/assets/flags/cpv.png',
  ),
  Country(
    countryCode: CountryCode.ky,
    name: 'Cayman Islands',
    callCode: '+1345',
    flag: 'packages/country_calling_code_kit/assets/flags/cym.png',
  ),
  Country(
    countryCode: CountryCode.cf,
    name: 'Central African Republic',
    callCode: '+236',
    flag: 'packages/country_calling_code_kit/assets/flags/caf.png',
  ),
  Country(
    countryCode: CountryCode.td,
    name: 'Chad',
    callCode: '+235',
    flag: 'packages/country_calling_code_kit/assets/flags/tcd.png',
  ),
  Country(
    countryCode: CountryCode.cl,
    name: 'Chile',
    callCode: '+56',
    flag: 'packages/country_calling_code_kit/assets/flags/chl.png',
  ),
  Country(
    countryCode: CountryCode.cn,
    name: 'China',
    callCode: '+86',
    flag: 'packages/country_calling_code_kit/assets/flags/chn.png',
  ),
  Country(
    countryCode: CountryCode.cx,
    name: 'Christmas Island',
    callCode: '+61',
    flag: 'packages/country_calling_code_kit/assets/flags/cxr.png',
  ),
  Country(
    countryCode: CountryCode.cc,
    name: 'Cocos (Keeling) Islands',
    callCode: '+61',
    flag: 'packages/country_calling_code_kit/assets/flags/cck.png',
  ),
  Country(
    countryCode: CountryCode.co,
    name: 'Colombia',
    callCode: '+57',
    flag: 'packages/country_calling_code_kit/assets/flags/col.png',
  ),
  Country(
    countryCode: CountryCode.km,
    name: 'Comoros',
    callCode: '+269',
    flag: 'packages/country_calling_code_kit/assets/flags/com.png',
  ),
  Country(
    countryCode: CountryCode.cg,
    name: 'Congo',
    callCode: '+242',
    flag: 'packages/country_calling_code_kit/assets/flags/cog.png',
  ),
  Country(
    countryCode: CountryCode.cd,
    name: 'Congo (Democratic Republic of the)',
    callCode: '+243',
    flag: 'packages/country_calling_code_kit/assets/flags/cod.png',
  ),
  Country(
    countryCode: CountryCode.ck,
    name: 'Cook Islands',
    callCode: '+682',
    flag: 'packages/country_calling_code_kit/assets/flags/cok.png',
  ),
  Country(
    countryCode: CountryCode.cr,
    name: 'Costa Rica',
    callCode: '+506',
    flag: 'packages/country_calling_code_kit/assets/flags/cri.png',
  ),
  Country(
    countryCode: CountryCode.hr,
    name: 'Croatia',
    callCode: '+385',
    flag: 'packages/country_calling_code_kit/assets/flags/hrv.png',
  ),
  Country(
    countryCode: CountryCode.cu,
    name: 'Cuba',
    callCode: '+53',
    flag: 'packages/country_calling_code_kit/assets/flags/cub.png',
  ),
  Country(
    countryCode: CountryCode.cw,
    name: 'Curaçao',
    callCode: '+599',
    flag: 'packages/country_calling_code_kit/assets/flags/cuw.png',
  ),
  Country(
    countryCode: CountryCode.cy,
    name: 'Cyprus',
    callCode: '+357',
    flag: 'packages/country_calling_code_kit/assets/flags/cyp.png',
  ),
  Country(
    countryCode: CountryCode.cz,
    name: 'Czech Republic',
    callCode: '+420',
    flag: 'packages/country_calling_code_kit/assets/flags/cze.png',
  ),
  Country(
    countryCode: CountryCode.dk,
    name: 'Denmark',
    callCode: '+45',
    flag: 'packages/country_calling_code_kit/assets/flags/dnk.png',
  ),
  Country(
    countryCode: CountryCode.dj,
    name: 'Djibouti',
    callCode: '+253',
    flag: 'packages/country_calling_code_kit/assets/flags/dji.png',
  ),
  Country(
    countryCode: CountryCode.dm,
    name: 'Dominica',
    callCode: '+1767',
    flag: 'packages/country_calling_code_kit/assets/flags/dma.png',
  ),
  Country(
    countryCode: CountryCode.do_,
    name: 'Dominican Republic',
    callCode: '+1809',
    flag: 'packages/country_calling_code_kit/assets/flags/dom.png',
  ),
  Country(
    countryCode: CountryCode.ec,
    name: 'Ecuador',
    callCode: '+593',
    flag: 'packages/country_calling_code_kit/assets/flags/ecu.png',
  ),
  Country(
    countryCode: CountryCode.eg,
    name: 'Egypt',
    callCode: '+20',
    flag: 'packages/country_calling_code_kit/assets/flags/egy.png',
  ),
  Country(
    countryCode: CountryCode.sv,
    name: 'El Salvador',
    callCode: '+503',
    flag: 'packages/country_calling_code_kit/assets/flags/slv.png',
  ),
  Country(
    countryCode: CountryCode.gq,
    name: 'Equatorial Guinea',
    callCode: '+240',
    flag: 'packages/country_calling_code_kit/assets/flags/gnq.png',
  ),
  Country(
    countryCode: CountryCode.er,
    name: 'Eritrea',
    callCode: '+291',
    flag: 'packages/country_calling_code_kit/assets/flags/eri.png',
  ),
  Country(
    countryCode: CountryCode.ee,
    name: 'Estonia',
    callCode: '+372',
    flag: 'packages/country_calling_code_kit/assets/flags/est.png',
  ),
  Country(
    countryCode: CountryCode.et,
    name: 'Ethiopia',
    callCode: '+251',
    flag: 'packages/country_calling_code_kit/assets/flags/eth.png',
  ),
  Country(
    countryCode: CountryCode.fk,
    name: 'Falkland Islands (Malvinas)',
    callCode: '+500',
    flag: 'packages/country_calling_code_kit/assets/flags/flk.png',
  ),
  Country(
    countryCode: CountryCode.fo,
    name: 'Faroe Islands',
    callCode: '+298',
    flag: 'packages/country_calling_code_kit/assets/flags/fro.png',
  ),
  Country(
    countryCode: CountryCode.fj,
    name: 'Fiji',
    callCode: '+679',
    flag: 'packages/country_calling_code_kit/assets/flags/fji.png',
  ),
  Country(
    countryCode: CountryCode.fi,
    name: 'Finland',
    callCode: '+358',
    flag: 'packages/country_calling_code_kit/assets/flags/fin.png',
  ),
  Country(
    countryCode: CountryCode.fr,
    name: 'France',
    callCode: '+33',
    flag: 'packages/country_calling_code_kit/assets/flags/fra.png',
  ),
  Country(
    countryCode: CountryCode.gf,
    name: 'French Guiana',
    callCode: '+594',
    flag: 'packages/country_calling_code_kit/assets/flags/guf.png',
  ),
  Country(
    countryCode: CountryCode.pf,
    name: 'French Polynesia',
    callCode: '+689',
    flag: 'packages/country_calling_code_kit/assets/flags/pyf.png',
  ),
  Country(
    countryCode: CountryCode.tf,
    name: 'French Southern Territories',
    callCode: '+262',
    flag: 'packages/country_calling_code_kit/assets/flags/atf.png',
  ),
  Country(
    countryCode: CountryCode.ga,
    name: 'Gabon',
    callCode: '+241',
    flag: 'packages/country_calling_code_kit/assets/flags/gab.png',
  ),
  Country(
    countryCode: CountryCode.gm,
    name: 'Gambia',
    callCode: '+220',
    flag: 'packages/country_calling_code_kit/assets/flags/gmb.png',
  ),
  Country(
    countryCode: CountryCode.ge,
    name: 'Georgia',
    callCode: '+995',
    flag: 'packages/country_calling_code_kit/assets/flags/geo.png',
  ),
  Country(
    countryCode: CountryCode.de,
    name: 'Germany',
    callCode: '+49',
    flag: 'packages/country_calling_code_kit/assets/flags/deu.png',
  ),
  Country(
    countryCode: CountryCode.gh,
    name: 'Ghana',
    callCode: '+233',
    flag: 'packages/country_calling_code_kit/assets/flags/gha.png',
  ),
  Country(
    countryCode: CountryCode.gi,
    name: 'Gibraltar',
    callCode: '+350',
    flag: 'packages/country_calling_code_kit/assets/flags/gib.png',
  ),
  Country(
    countryCode: CountryCode.gr,
    name: 'Greece',
    callCode: '+30',
    flag: 'packages/country_calling_code_kit/assets/flags/grc.png',
  ),
  Country(
    countryCode: CountryCode.gl,
    name: 'Greenland',
    callCode: '+299',
    flag: 'packages/country_calling_code_kit/assets/flags/grl.png',
  ),
  Country(
    countryCode: CountryCode.gd,
    name: 'Grenada',
    callCode: '+1473',
    flag: 'packages/country_calling_code_kit/assets/flags/grd.png',
  ),
  Country(
    countryCode: CountryCode.gp,
    name: 'Guadeloupe',
    callCode: '+590',
    flag: 'packages/country_calling_code_kit/assets/flags/glp.png',
  ),
  Country(
    countryCode: CountryCode.gu,
    name: 'Guam',
    callCode: '+1671',
    flag: 'packages/country_calling_code_kit/assets/flags/gum.png',
  ),
  Country(
    countryCode: CountryCode.gt,
    name: 'Guatemala',
    callCode: '+502',
    flag: 'packages/country_calling_code_kit/assets/flags/gtm.png',
  ),
  Country(
    countryCode: CountryCode.gg,
    name: 'Guernsey',
    callCode: '+44',
    flag: 'packages/country_calling_code_kit/assets/flags/ggy.png',
  ),
  Country(
    countryCode: CountryCode.gn,
    name: 'Guinea',
    callCode: '+224',
    flag: 'packages/country_calling_code_kit/assets/flags/gin.png',
  ),
  Country(
    countryCode: CountryCode.gw,
    name: 'Guinea-Bissau',
    callCode: '+245',
    flag: 'packages/country_calling_code_kit/assets/flags/gnb.png',
  ),
  Country(
    countryCode: CountryCode.gy,
    name: 'Guyana',
    callCode: '+592',
    flag: 'packages/country_calling_code_kit/assets/flags/guy.png',
  ),
  Country(
    countryCode: CountryCode.ht,
    name: 'Haiti',
    callCode: '+509',
    flag: 'packages/country_calling_code_kit/assets/flags/hti.png',
  ),
  Country(
    countryCode: CountryCode.hm,
    name: 'Heard Island and McDonald Islands',
    callCode: '+672',
    flag: 'packages/country_calling_code_kit/assets/flags/hmd.png',
  ),
  Country(
    countryCode: CountryCode.va,
    name: 'Holy See',
    callCode: '+379',
    flag: 'packages/country_calling_code_kit/assets/flags/vat.png',
  ),
  Country(
    countryCode: CountryCode.hn,
    name: 'Honduras',
    callCode: '+504',
    flag: 'packages/country_calling_code_kit/assets/flags/hnd.png',
  ),
  Country(
    countryCode: CountryCode.hk,
    name: 'Hong Kong',
    callCode: '+852',
    flag: 'packages/country_calling_code_kit/assets/flags/hkg.png',
  ),
  Country(
    countryCode: CountryCode.hu,
    name: 'Hungary',
    callCode: '+36',
    flag: 'packages/country_calling_code_kit/assets/flags/hun.png',
  ),
  Country(
    countryCode: CountryCode.is_,
    name: 'Iceland',
    callCode: '+354',
    flag: 'packages/country_calling_code_kit/assets/flags/isl.png',
  ),
  Country(
    countryCode: CountryCode.in_,
    name: 'India',
    callCode: '+91',
    flag: 'packages/country_calling_code_kit/assets/flags/ind.png',
  ),
  Country(
    countryCode: CountryCode.id,
    name: 'Indonesia',
    callCode: '+62',
    flag: 'packages/country_calling_code_kit/assets/flags/idn.png',
  ),
  Country(
    countryCode: CountryCode.ci,
    name: 'Côte d\'Ivoire',
    callCode: '+225',
    flag: 'packages/country_calling_code_kit/assets/flags/civ.png',
  ),
  Country(
    countryCode: CountryCode.ir,
    name: 'Iran (Islamic Republic of)',
    callCode: '+98',
    flag: 'packages/country_calling_code_kit/assets/flags/irn.png',
  ),
  Country(
    countryCode: CountryCode.iq,
    name: 'Iraq',
    callCode: '+964',
    flag: 'packages/country_calling_code_kit/assets/flags/irq.png',
  ),
  Country(
    countryCode: CountryCode.ie,
    name: 'Ireland',
    callCode: '+353',
    flag: 'packages/country_calling_code_kit/assets/flags/irl.png',
  ),
  Country(
    countryCode: CountryCode.im,
    name: 'Isle of Man',
    callCode: '+44',
    flag: 'packages/country_calling_code_kit/assets/flags/imn.png',
  ),
  Country(
    countryCode: CountryCode.il,
    name: 'Israel',
    callCode: '+972',
    flag: 'packages/country_calling_code_kit/assets/flags/isr.png',
  ),
  Country(
    countryCode: CountryCode.it,
    name: 'Italy',
    callCode: '+39',
    flag: 'packages/country_calling_code_kit/assets/flags/ita.png',
  ),
  Country(
    countryCode: CountryCode.jm,
    name: 'Jamaica',
    callCode: '+1876',
    flag: 'packages/country_calling_code_kit/assets/flags/jam.png',
  ),
  Country(
    countryCode: CountryCode.jp,
    name: 'Japan',
    callCode: '+81',
    flag: 'packages/country_calling_code_kit/assets/flags/jpn.png',
  ),
  Country(
    countryCode: CountryCode.je,
    name: 'Jersey',
    callCode: '+44',
    flag: 'packages/country_calling_code_kit/assets/flags/jey.png',
  ),
  Country(
    countryCode: CountryCode.jo,
    name: 'Jordan',
    callCode: '+962',
    flag: 'packages/country_calling_code_kit/assets/flags/jor.png',
  ),
  Country(
    countryCode: CountryCode.kz,
    name: 'Kazakhstan',
    callCode: '+76',
    flag: 'packages/country_calling_code_kit/assets/flags/kaz.png',
  ),
  Country(
    countryCode: CountryCode.ke,
    name: 'Kenya',
    callCode: '+254',
    flag: 'packages/country_calling_code_kit/assets/flags/ken.png',
  ),
  Country(
    countryCode: CountryCode.ki,
    name: 'Kiribati',
    callCode: '+686',
    flag: 'packages/country_calling_code_kit/assets/flags/kir.png',
  ),
  Country(
    countryCode: CountryCode.kw,
    name: 'Kuwait',
    callCode: '+965',
    flag: 'packages/country_calling_code_kit/assets/flags/kwt.png',
  ),
  Country(
    countryCode: CountryCode.kg,
    name: 'Kyrgyzstan',
    callCode: '+996',
    flag: 'packages/country_calling_code_kit/assets/flags/kgz.png',
  ),
  Country(
    countryCode: CountryCode.la,
    name: 'Lao People\'s Democratic Republic',
    callCode: '+856',
    flag: 'packages/country_calling_code_kit/assets/flags/lao.png',
  ),
  Country(
    countryCode: CountryCode.lv,
    name: 'Latvia',
    callCode: '+371',
    flag: 'packages/country_calling_code_kit/assets/flags/lva.png',
  ),
  Country(
    countryCode: CountryCode.lb,
    name: 'Lebanon',
    callCode: '+961',
    flag: 'packages/country_calling_code_kit/assets/flags/lbn.png',
  ),
  Country(
    countryCode: CountryCode.ls,
    name: 'Lesotho',
    callCode: '+266',
    flag: 'packages/country_calling_code_kit/assets/flags/lso.png',
  ),
  Country(
    countryCode: CountryCode.lr,
    name: 'Liberia',
    callCode: '+231',
    flag: 'packages/country_calling_code_kit/assets/flags/lbr.png',
  ),
  Country(
    countryCode: CountryCode.ly,
    name: 'Libya',
    callCode: '+218',
    flag: 'packages/country_calling_code_kit/assets/flags/lby.png',
  ),
  Country(
    countryCode: CountryCode.li,
    name: 'Liechtenstein',
    callCode: '+423',
    flag: 'packages/country_calling_code_kit/assets/flags/lie.png',
  ),
  Country(
    countryCode: CountryCode.lt,
    name: 'Lithuania',
    callCode: '+370',
    flag: 'packages/country_calling_code_kit/assets/flags/ltu.png',
  ),
  Country(
    countryCode: CountryCode.lu,
    name: 'Luxembourg',
    callCode: '+352',
    flag: 'packages/country_calling_code_kit/assets/flags/lux.png',
  ),
  Country(
    countryCode: CountryCode.mo,
    name: 'Macao',
    callCode: '+853',
    flag: 'packages/country_calling_code_kit/assets/flags/mac.png',
  ),
  Country(
    countryCode: CountryCode.mk,
    name: 'Macedonia (the former Yugoslav Republic of)',
    callCode: '+389',
    flag: 'packages/country_calling_code_kit/assets/flags/mkd.png',
  ),
  Country(
    countryCode: CountryCode.mg,
    name: 'Madagascar',
    callCode: '+261',
    flag: 'packages/country_calling_code_kit/assets/flags/mdg.png',
  ),
  Country(
    countryCode: CountryCode.mw,
    name: 'Malawi',
    callCode: '+265',
    flag: 'packages/country_calling_code_kit/assets/flags/mwi.png',
  ),
  Country(
    countryCode: CountryCode.my,
    name: 'Malaysia',
    callCode: '+60',
    flag: 'packages/country_calling_code_kit/assets/flags/mys.png',
  ),
  Country(
    countryCode: CountryCode.mv,
    name: 'Maldives',
    callCode: '+960',
    flag: 'packages/country_calling_code_kit/assets/flags/mdv.png',
  ),
  Country(
    countryCode: CountryCode.ml,
    name: 'Mali',
    callCode: '+223',
    flag: 'packages/country_calling_code_kit/assets/flags/mli.png',
  ),
  Country(
    countryCode: CountryCode.mt,
    name: 'Malta',
    callCode: '+356',
    flag: 'packages/country_calling_code_kit/assets/flags/mlt.png',
  ),
  Country(
    countryCode: CountryCode.mh,
    name: 'Marshall Islands',
    callCode: '+692',
    flag: 'packages/country_calling_code_kit/assets/flags/mhl.png',
  ),
  Country(
    countryCode: CountryCode.mq,
    name: 'Martinique',
    callCode: '+596',
    flag: 'packages/country_calling_code_kit/assets/flags/mtq.png',
  ),
  Country(
    countryCode: CountryCode.mr,
    name: 'Mauritania',
    callCode: '+222',
    flag: 'packages/country_calling_code_kit/assets/flags/mrt.png',
  ),
  Country(
    countryCode: CountryCode.mu,
    name: 'Mauritius',
    callCode: '+230',
    flag: 'packages/country_calling_code_kit/assets/flags/mus.png',
  ),
  Country(
    countryCode: CountryCode.yt,
    name: 'Mayotte',
    callCode: '+262',
    flag: 'packages/country_calling_code_kit/assets/flags/myt.png',
  ),
  Country(
    countryCode: CountryCode.mx,
    name: 'Mexico',
    callCode: '+52',
    flag: 'packages/country_calling_code_kit/assets/flags/mex.png',
  ),
  Country(
    countryCode: CountryCode.fm,
    name: 'Micronesia (Federated States of)',
    callCode: '+691',
    flag: 'packages/country_calling_code_kit/assets/flags/fsm.png',
  ),
  Country(
    countryCode: CountryCode.md,
    name: 'Moldova (Republic of)',
    callCode: '+373',
    flag: 'packages/country_calling_code_kit/assets/flags/mda.png',
  ),
  Country(
    countryCode: CountryCode.mc,
    name: 'Monaco',
    callCode: '+377',
    flag: 'packages/country_calling_code_kit/assets/flags/mco.png',
  ),
  Country(
    countryCode: CountryCode.mn,
    name: 'Mongolia',
    callCode: '+976',
    flag: 'packages/country_calling_code_kit/assets/flags/mng.png',
  ),
  Country(
    countryCode: CountryCode.me,
    name: 'Montenegro',
    callCode: '+382',
    flag: 'packages/country_calling_code_kit/assets/flags/mne.png',
  ),
  Country(
    countryCode: CountryCode.ms,
    name: 'Montserrat',
    callCode: '+1664',
    flag: 'packages/country_calling_code_kit/assets/flags/msr.png',
  ),
  Country(
    countryCode: CountryCode.ma,
    name: 'Morocco',
    callCode: '+212',
    flag: 'packages/country_calling_code_kit/assets/flags/mar.png',
  ),
  Country(
    countryCode: CountryCode.mz,
    name: 'Mozambique',
    callCode: '+258',
    flag: 'packages/country_calling_code_kit/assets/flags/moz.png',
  ),
  Country(
    countryCode: CountryCode.mm,
    name: 'Myanmar',
    callCode: '+95',
    flag: 'packages/country_calling_code_kit/assets/flags/mmr.png',
  ),
  Country(
    countryCode: CountryCode.na,
    name: 'Namibia',
    callCode: '+264',
    flag: 'packages/country_calling_code_kit/assets/flags/nam.png',
  ),
  Country(
    countryCode: CountryCode.nr,
    name: 'Nauru',
    callCode: '+674',
    flag: 'packages/country_calling_code_kit/assets/flags/nru.png',
  ),
  Country(
    countryCode: CountryCode.np,
    name: 'Nepal',
    callCode: '+977',
    flag: 'packages/country_calling_code_kit/assets/flags/npl.png',
  ),
  Country(
    countryCode: CountryCode.nl,
    name: 'Netherlands',
    callCode: '+31',
    flag: 'packages/country_calling_code_kit/assets/flags/nld.png',
  ),
  Country(
    countryCode: CountryCode.nc,
    name: 'New Caledonia',
    callCode: '+687',
    flag: 'packages/country_calling_code_kit/assets/flags/ncl.png',
  ),
  Country(
    countryCode: CountryCode.nz,
    name: 'New Zealand',
    callCode: '+64',
    flag: 'packages/country_calling_code_kit/assets/flags/nzl.png',
  ),
  Country(
    countryCode: CountryCode.ni,
    name: 'Nicaragua',
    callCode: '+505',
    flag: 'packages/country_calling_code_kit/assets/flags/nic.png',
  ),
  Country(
    countryCode: CountryCode.ne,
    name: 'Niger',
    callCode: '+227',
    flag: 'packages/country_calling_code_kit/assets/flags/ner.png',
  ),
  Country(
    countryCode: CountryCode.ng,
    name: 'Nigeria',
    callCode: '+234',
    flag: 'packages/country_calling_code_kit/assets/flags/nga.png',
  ),
  Country(
    countryCode: CountryCode.nu,
    name: 'Niue',
    callCode: '+683',
    flag: 'packages/country_calling_code_kit/assets/flags/niu.png',
  ),
  Country(
    countryCode: CountryCode.nf,
    name: 'Norfolk Island',
    callCode: '+672',
    flag: 'packages/country_calling_code_kit/assets/flags/nfk.png',
  ),
  Country(
    countryCode: CountryCode.kp,
    name: 'Korea (Democratic People\'s Republic of)',
    callCode: '+850',
    flag: 'packages/country_calling_code_kit/assets/flags/prk.png',
  ),
  Country(
    countryCode: CountryCode.mp,
    name: 'Northern Mariana Islands',
    callCode: '+1670',
    flag: 'packages/country_calling_code_kit/assets/flags/mnp.png',
  ),
  Country(
    countryCode: CountryCode.no,
    name: 'Norway',
    callCode: '+47',
    flag: 'packages/country_calling_code_kit/assets/flags/nor.png',
  ),
  Country(
    countryCode: CountryCode.om,
    name: 'Oman',
    callCode: '+968',
    flag: 'packages/country_calling_code_kit/assets/flags/omn.png',
  ),
  Country(
    countryCode: CountryCode.pk,
    name: 'Pakistan',
    callCode: '+92',
    flag: 'packages/country_calling_code_kit/assets/flags/pak.png',
  ),
  Country(
    countryCode: CountryCode.pw,
    name: 'Palau',
    callCode: '+680',
    flag: 'packages/country_calling_code_kit/assets/flags/plw.png',
  ),
  Country(
    countryCode: CountryCode.ps,
    name: 'Palestine, State of',
    callCode: '+970',
    flag: 'packages/country_calling_code_kit/assets/flags/pse.png',
  ),
  Country(
    countryCode: CountryCode.pa,
    name: 'Panama',
    callCode: '+507',
    flag: 'packages/country_calling_code_kit/assets/flags/pan.png',
  ),
  Country(
    countryCode: CountryCode.pg,
    name: 'Papua New Guinea',
    callCode: '+675',
    flag: 'packages/country_calling_code_kit/assets/flags/png.png',
  ),
  Country(
    countryCode: CountryCode.py,
    name: 'Paraguay',
    callCode: '+595',
    flag: 'packages/country_calling_code_kit/assets/flags/pry.png',
  ),
  Country(
    countryCode: CountryCode.pe,
    name: 'Peru',
    callCode: '+51',
    flag: 'packages/country_calling_code_kit/assets/flags/per.png',
  ),
  Country(
    countryCode: CountryCode.ph,
    name: 'Philippines',
    callCode: '+63',
    flag: 'packages/country_calling_code_kit/assets/flags/phl.png',
  ),
  Country(
    countryCode: CountryCode.pn,
    name: 'Pitcairn',
    callCode: '+64',
    flag: 'packages/country_calling_code_kit/assets/flags/pcn.png',
  ),
  Country(
    countryCode: CountryCode.pl,
    name: 'Poland',
    callCode: '+48',
    flag: 'packages/country_calling_code_kit/assets/flags/pol.png',
  ),
  Country(
    countryCode: CountryCode.pt,
    name: 'Portugal',
    callCode: '+351',
    flag: 'packages/country_calling_code_kit/assets/flags/prt.png',
  ),
  Country(
    countryCode: CountryCode.pr,
    name: 'Puerto Rico',
    callCode: '+1787',
    flag: 'packages/country_calling_code_kit/assets/flags/pri.png',
  ),
  Country(
    countryCode: CountryCode.qa,
    name: 'Qatar',
    callCode: '+974',
    flag: 'packages/country_calling_code_kit/assets/flags/qat.png',
  ),
  Country(
    countryCode: CountryCode.xk,
    name: 'Republic of Kosovo',
    callCode: '+383',
    flag: 'packages/country_calling_code_kit/assets/flags/kos.png',
  ),
  Country(
    countryCode: CountryCode.re,
    name: 'Réunion',
    callCode: '+262',
    flag: 'packages/country_calling_code_kit/assets/flags/reu.png',
  ),
  Country(
    countryCode: CountryCode.ro,
    name: 'Romania',
    callCode: '+40',
    flag: 'packages/country_calling_code_kit/assets/flags/rou.png',
  ),
  Country(
    countryCode: CountryCode.ru,
    name: 'Russian Federation',
    callCode: '+7',
    flag: 'packages/country_calling_code_kit/assets/flags/rus.png',
  ),
  Country(
    countryCode: CountryCode.rw,
    name: 'Rwanda',
    callCode: '+250',
    flag: 'packages/country_calling_code_kit/assets/flags/rwa.png',
  ),
  Country(
    countryCode: CountryCode.bl,
    name: 'Saint Barthélemy',
    callCode: '+590',
    flag: 'packages/country_calling_code_kit/assets/flags/blm.png',
  ),
  Country(
    countryCode: CountryCode.sh,
    name: 'Saint Helena, Ascension and Tristan da Cunha',
    callCode: '+290',
    flag: 'packages/country_calling_code_kit/assets/flags/shn.png',
  ),
  Country(
    countryCode: CountryCode.kn,
    name: 'Saint Kitts and Nevis',
    callCode: '+1869',
    flag: 'packages/country_calling_code_kit/assets/flags/kna.png',
  ),
  Country(
    countryCode: CountryCode.lc,
    name: 'Saint Lucia',
    callCode: '+1758',
    flag: 'packages/country_calling_code_kit/assets/flags/lca.png',
  ),
  Country(
    countryCode: CountryCode.mf,
    name: 'Saint Martin (French part)',
    callCode: '+590',
    flag: 'packages/country_calling_code_kit/assets/flags/maf.png',
  ),
  Country(
    countryCode: CountryCode.pm,
    name: 'Saint Pierre and Miquelon',
    callCode: '+508',
    flag: 'packages/country_calling_code_kit/assets/flags/spm.png',
  ),
  Country(
    countryCode: CountryCode.vc,
    name: 'Saint Vincent and the Grenadines',
    callCode: '+1784',
    flag: 'packages/country_calling_code_kit/assets/flags/vct.png',
  ),
  Country(
    countryCode: CountryCode.ws,
    name: 'Samoa',
    callCode: '+685',
    flag: 'packages/country_calling_code_kit/assets/flags/wsm.png',
  ),
  Country(
    countryCode: CountryCode.sm,
    name: 'San Marino',
    callCode: '+378',
    flag: 'packages/country_calling_code_kit/assets/flags/smr.png',
  ),
  Country(
    countryCode: CountryCode.st,
    name: 'Sao Tome and Principe',
    callCode: '+239',
    flag: 'packages/country_calling_code_kit/assets/flags/stp.png',
  ),
  Country(
    countryCode: CountryCode.sa,
    name: 'Saudi Arabia',
    callCode: '+966',
    flag: 'packages/country_calling_code_kit/assets/flags/sau.png',
  ),
  Country(
    countryCode: CountryCode.sn,
    name: 'Senegal',
    callCode: '+221',
    flag: 'packages/country_calling_code_kit/assets/flags/sen.png',
  ),
  Country(
    countryCode: CountryCode.rs,
    name: 'Serbia',
    callCode: '+381',
    flag: 'packages/country_calling_code_kit/assets/flags/srb.png',
  ),
  Country(
    countryCode: CountryCode.sc,
    name: 'Seychelles',
    callCode: '+248',
    flag: 'packages/country_calling_code_kit/assets/flags/syc.png',
  ),
  Country(
    countryCode: CountryCode.sl,
    name: 'Sierra Leone',
    callCode: '+232',
    flag: 'packages/country_calling_code_kit/assets/flags/sle.png',
  ),
  Country(
    countryCode: CountryCode.sg,
    name: 'Singapore',
    callCode: '+65',
    flag: 'packages/country_calling_code_kit/assets/flags/sgp.png',
  ),
  Country(
    countryCode: CountryCode.sx,
    name: 'Sint Maarten (Dutch part)',
    callCode: '+1721',
    flag: 'packages/country_calling_code_kit/assets/flags/sxm.png',
  ),
  Country(
    countryCode: CountryCode.sk,
    name: 'Slovakia',
    callCode: '+421',
    flag: 'packages/country_calling_code_kit/assets/flags/svk.png',
  ),
  Country(
    countryCode: CountryCode.si,
    name: 'Slovenia',
    callCode: '+386',
    flag: 'packages/country_calling_code_kit/assets/flags/svn.png',
  ),
  Country(
    countryCode: CountryCode.sb,
    name: 'Solomon Islands',
    callCode: '+677',
    flag: 'packages/country_calling_code_kit/assets/flags/slb.png',
  ),
  Country(
    countryCode: CountryCode.so,
    name: 'Somalia',
    callCode: '+252',
    flag: 'packages/country_calling_code_kit/assets/flags/som.png',
  ),
  Country(
    countryCode: CountryCode.za,
    name: 'South Africa',
    callCode: '+27',
    flag: 'packages/country_calling_code_kit/assets/flags/zaf.png',
  ),
  Country(
    countryCode: CountryCode.gs,
    name: 'South Georgia and the South Sandwich Islands',
    callCode: '+500',
    flag: 'packages/country_calling_code_kit/assets/flags/sgs.png',
  ),
  Country(
    countryCode: CountryCode.kr,
    name: 'Korea (Republic of)',
    callCode: '+82',
    flag: 'packages/country_calling_code_kit/assets/flags/kor.png',
  ),
  Country(
    countryCode: CountryCode.ss,
    name: 'South Sudan',
    callCode: '+211',
    flag: 'packages/country_calling_code_kit/assets/flags/ssd.png',
  ),
  Country(
    countryCode: CountryCode.es,
    name: 'Spain',
    callCode: '+34',
    flag: 'packages/country_calling_code_kit/assets/flags/esp.png',
  ),
  Country(
    countryCode: CountryCode.lk,
    name: 'Sri Lanka',
    callCode: '+94',
    flag: 'packages/country_calling_code_kit/assets/flags/lka.png',
  ),
  Country(
    countryCode: CountryCode.sd,
    name: 'Sudan',
    callCode: '+249',
    flag: 'packages/country_calling_code_kit/assets/flags/sdn.png',
  ),
  Country(
    countryCode: CountryCode.sr,
    name: 'Suriname',
    callCode: '+597',
    flag: 'packages/country_calling_code_kit/assets/flags/sur.png',
  ),
  Country(
    countryCode: CountryCode.sj,
    name: 'Svalbard and Jan Mayen',
    callCode: '+4779',
    flag: 'packages/country_calling_code_kit/assets/flags/sjm.png',
  ),
  Country(
    countryCode: CountryCode.sz,
    name: 'Swaziland',
    callCode: '+268',
    flag: 'packages/country_calling_code_kit/assets/flags/swz.png',
  ),
  Country(
    countryCode: CountryCode.se,
    name: 'Sweden',
    callCode: '+46',
    flag: 'packages/country_calling_code_kit/assets/flags/swe.png',
  ),
  Country(
    countryCode: CountryCode.ch,
    name: 'Switzerland',
    callCode: '+41',
    flag: 'packages/country_calling_code_kit/assets/flags/che.png',
  ),
  Country(
    countryCode: CountryCode.sy,
    name: 'Syrian Arab Republic',
    callCode: '+963',
    flag: 'packages/country_calling_code_kit/assets/flags/syr.png',
  ),
  Country(
    countryCode: CountryCode.tw,
    name: 'Taiwan',
    callCode: '+886',
    flag: 'packages/country_calling_code_kit/assets/flags/twn.png',
  ),
  Country(
    countryCode: CountryCode.tj,
    name: 'Tajikistan',
    callCode: '+992',
    flag: 'packages/country_calling_code_kit/assets/flags/tjk.png',
  ),
  Country(
    countryCode: CountryCode.tz,
    name: 'Tanzania, United Republic of',
    callCode: '+255',
    flag: 'packages/country_calling_code_kit/assets/flags/tza.png',
  ),
  Country(
    countryCode: CountryCode.th,
    name: 'Thailand',
    callCode: '+66',
    flag: 'packages/country_calling_code_kit/assets/flags/tha.png',
  ),
  Country(
    countryCode: CountryCode.tl,
    name: 'Timor-Leste',
    callCode: '+670',
    flag: 'packages/country_calling_code_kit/assets/flags/tls.png',
  ),
  Country(
    countryCode: CountryCode.tg,
    name: 'Togo',
    callCode: '+228',
    flag: 'packages/country_calling_code_kit/assets/flags/tgo.png',
  ),
  Country(
    countryCode: CountryCode.tk,
    name: 'Tokelau',
    callCode: '+690',
    flag: 'packages/country_calling_code_kit/assets/flags/tkl.png',
  ),
  Country(
    countryCode: CountryCode.to,
    name: 'Tonga',
    callCode: '+676',
    flag: 'packages/country_calling_code_kit/assets/flags/ton.png',
  ),
  Country(
    countryCode: CountryCode.tt,
    name: 'Trinidad and Tobago',
    callCode: '+1868',
    flag: 'packages/country_calling_code_kit/assets/flags/tto.png',
  ),
  Country(
    countryCode: CountryCode.tn,
    name: 'Tunisia',
    callCode: '+216',
    flag: 'packages/country_calling_code_kit/assets/flags/tun.png',
  ),
  Country(
    countryCode: CountryCode.tr,
    name: 'Turkey',
    callCode: '+90',
    flag: 'packages/country_calling_code_kit/assets/flags/tur.png',
  ),
  Country(
    countryCode: CountryCode.tm,
    name: 'Turkmenistan',
    callCode: '+993',
    flag: 'packages/country_calling_code_kit/assets/flags/tkm.png',
  ),
  Country(
    countryCode: CountryCode.tc,
    name: 'Turks and Caicos Islands',
    callCode: '+1649',
    flag: 'packages/country_calling_code_kit/assets/flags/tca.png',
  ),
  Country(
    countryCode: CountryCode.tv,
    name: 'Tuvalu',
    callCode: '+688',
    flag: 'packages/country_calling_code_kit/assets/flags/tuv.png',
  ),
  Country(
    countryCode: CountryCode.ug,
    name: 'Uganda',
    callCode: '+256',
    flag: 'packages/country_calling_code_kit/assets/flags/uga.png',
  ),
  Country(
    countryCode: CountryCode.ua,
    name: 'Ukraine',
    callCode: '+380',
    flag: 'packages/country_calling_code_kit/assets/flags/ukr.png',
  ),
  Country(
    countryCode: CountryCode.ae,
    name: 'United Arab Emirates',
    callCode: '+971',
    flag: 'packages/country_calling_code_kit/assets/flags/are.png',
  ),
  Country(
    countryCode: CountryCode.gb,
    name: 'United Kingdom of Great Britain and Northern Ireland',
    callCode: '+44',
    flag: 'packages/country_calling_code_kit/assets/flags/gbr.png',
  ),
  Country(
    countryCode: CountryCode.us,
    name: 'United States of America',
    callCode: '+1',
    flag: 'packages/country_calling_code_kit/assets/flags/usa.png',
  ),
  Country(
    countryCode: CountryCode.uy,
    name: 'Uruguay',
    callCode: '+598',
    flag: 'packages/country_calling_code_kit/assets/flags/ury.png',
  ),
  Country(
    countryCode: CountryCode.uz,
    name: 'Uzbekistan',
    callCode: '+998',
    flag: 'packages/country_calling_code_kit/assets/flags/uzb.png',
  ),
  Country(
    countryCode: CountryCode.vu,
    name: 'Vanuatu',
    callCode: '+678',
    flag: 'packages/country_calling_code_kit/assets/flags/vut.png',
  ),
  Country(
    countryCode: CountryCode.ve,
    name: 'Venezuela (Bolivarian Republic of)',
    callCode: '+58',
    flag: 'packages/country_calling_code_kit/assets/flags/ven.png',
  ),
  Country(
    countryCode: CountryCode.vn,
    name: 'Viet Nam',
    callCode: '+84',
    flag: 'packages/country_calling_code_kit/assets/flags/vnm.png',
  ),
  Country(
    countryCode: CountryCode.wf,
    name: 'Wallis and Futuna',
    callCode: '+681',
    flag: 'packages/country_calling_code_kit/assets/flags/wlf.png',
  ),
  Country(
    countryCode: CountryCode.eh,
    name: 'Western Sahara',
    callCode: '+212',
    flag: 'packages/country_calling_code_kit/assets/flags/esh.png',
  ),
  Country(
    countryCode: CountryCode.ye,
    name: 'Yemen',
    callCode: '+967',
    flag: 'packages/country_calling_code_kit/assets/flags/yem.png',
  ),
  Country(
    countryCode: CountryCode.zm,
    name: 'Zambia',
    callCode: '+260',
    flag: 'packages/country_calling_code_kit/assets/flags/zmb.png',
  ),
  Country(
    countryCode: CountryCode.zw,
    name: 'Zimbabwe',
    callCode: '+263',
    flag: 'packages/country_calling_code_kit/assets/flags/zwe.png',
  ),
];
